# 应用名称
spring:
  application:
    name: canto-to-redis
  redis:
    host: 192.168.25.131
    password: redis
    database: 0
canal:
  server: 127.0.0.1:11111
  destination: redis # 实例名

# 应用服务 WEB 访问端口
server:
  port: 8080

# 设置canal消息日志打印级别
logging:
  level:
    top.javatool.canal.client: warn
